Starter 1.1.0 rc1
enonic/starter-react4xp pull request #49
Opened 2020-09-22 19:14 UTC by espen42

Nevermind each single commit, just look at the final diff.

2020-09-22 21:26 UTC, sigdestad requested changes
Ser lugnt ut for meg, med unntak av important kommentaren. Guillotine er kun et read-only api. Fint om du tar bort all denne skremmingen :)

2020-09-22 21:42 UTC, sigdestad commented
Hmm, har du også committa grafikkfiler til demo inn i starteren?

2020-09-23 08:01 UTC, poi33 commented
@sigdestad du kan gjøre oppdateringer med graphql. Støtter vi det ikke?

2020-09-23 08:12 UTC, poi33 commented on docs/README.src.md
> +1. Install the starter from [Enonic Market](https://market.enonic.com/vendors/enonic/react4xp-starter) or clone it down from [the github repo](https://github.com/enonic/starter-react4xp).
Gir det noe mening å laste den ned fra market? Er ikke en starter noe du alltid vil utvikle på?

2020-09-23 08:12 UTC, sigdestad commented
Det forutsetter jo at man implementerer "mutations" - det har vi bevisst valgt å ikke gjøre så langt i Guillotine. Det er et rent "read-only" api.

2020-09-23 09:40 UTC, poi33 requested changes
Tror ikke vi kan legge til film plakater i en starter som vi gir ut. 
Liker heller ikke å legge til kode som må fjernes når noen skal bruke starteren i eget prosjekt

2020-09-23 09:40 UTC, poi33 commented on src/main/resources/headless/guillotineApi.es6
> + * - including mutating operations etc! It's meant for developers to expand from, and STRONGLY RECOMMENDED to implement
Apperently we don't support mutations :/ 
So you can only view all data that is in all of our repoes.

2020-09-23 09:40 UTC, poi33 commented on src/main/resources/headless/guillotineApi.es6
> +    log.info("body.variables (" +
I cant approve of this print out. It is to complexly nested into eachother. 
Just print body variables as JSON. Starters need to be as simple as possible to understand and use.

2020-09-23 09:40 UTC, poi33 commented on src/main/resources/headless/guillotineRequest.es6
> +        catchErrorsFunc: params.catchErrorsFunc || ( error => {console.error(error);} )
console.error is this not a possible server side run code?

2020-09-23 09:40 UTC, poi33 commented on src/main/resources/site/pages/default/default.es6
> +    output.body = '<!DOCTYPE html>' + output.body;
This is a nice solution to the breaking render. Could this be handled in react4xp? Some simple check for that tag and remove it if its supplied. 
And prepend it to and <html></html> tag after rendering?

2020-09-23 10:17 UTC, sigdestad commented
Best practise nå er at starter skal bare skal inneholde det essensielle. Vi skal gjøre det samme med headless starteren. Ergo, demo innhold o.l. Bør ikke ligge direkte i starter. Hva du gjør ifm demo er det samme for meg :-)

2020-09-23 13:22 UTC, espen42 commented on docs/README.src.md
> +1. Install the starter from [Enonic Market](https://market.enonic.com/vendors/enonic/react4xp-starter) or clone it down from [the github repo](https://github.com/enonic/starter-react4xp).
Sikkert. Men får fikse formuleringen en annen gang.

2020-09-23 13:42 UTC, espen42 reviewed
Glemte noen ting der ja.
- Fjernet postergrafikkfilene
- Fjernet log.info i guillotineApi
- Tonet ned skræmminga i important-kommentaren:

```
 * ------------   IMPORTANT!   --------------   IMPORTANT!   --------------   IMPORTANT!   --------------
 *
 * Before you add that mapping and expose this API, consider this:
 * This API is as-is, and as bare-bone as it gets. Guillotine is a read-only interface, but this endpoint still exposes
 * the possibility to send ANY QUERY, so any data will technically be readable from your repo.
 * This is meant for developers to expand from, and it's strongly recommended to implement your own security solution
 * according to your specific use case and requirements.
```

Og utsetter disse to endringene til neste utgave: https://github.com/enonic/starter-react4xp/issues/50

Da er vi good to go for å release starteren nå?

2020-09-23 13:42 UTC, espen42 commented on docs/README.src.md
> +    npm i
Gir mening. Fikser.

2020-09-23 13:42 UTC, espen42 commented on src/main/resources/headless/guillotineApi.es6
> + * - including mutating operations etc! It's meant for developers to expand from, and STRONGLY RECOMMENDED to implement
Denne må jeg endre nå, da.

2020-09-23 13:42 UTC, espen42 commented on src/main/resources/headless/guillotineApi.es6
> +    log.info("body.variables (" +
Good catch. Disse log.infoene skal ikke med i det hele tatt, rent dev-verktøy til meg selv.

2020-09-23 13:42 UTC, espen42 commented on src/main/resources/site/pages/default/default.es6
> +    output.body = '<!DOCTYPE html>' + output.body;
Good idea. Next iteration!

2020-09-23 13:42 UTC, espen42 commented on src/main/resources/headless/guillotineApi.es6
> + * - including mutating operations etc! It's meant for developers to expand from, and STRONGLY RECOMMENDED to implement
_Before you add that mapping and expose this API, consider this: This API is as-is, and as bare-bone as it gets. Guillotine is a read-only interface, but this endpoint still exposes the possibility to send ANY QUERY, so any data will technically be readable from your repo. This is meant for developers to expand from, and it's strongly recommended to implement your own security solution according to your specific use case and requirements._

2020-09-23 13:42 UTC, espen42 commented on src/main/resources/headless/guillotineRequest.es6
> +        catchErrorsFunc: params.catchErrorsFunc || ( error => {console.error(error);} )
No, this is a pure-frontend module.

2020-09-23 13:42 UTC, espen42 commented on src/main/resources/headless/guillotineRequest.es6
> +        catchErrorsFunc: params.catchErrorsFunc || ( error => {console.error(error);} )
It says so in the intro comment above. ;)

2020-09-23 18:51 UTC, merged